{
 "title": "Остановка общественного транспорта_Магазин Кристалл",
 "description": "test",
 "time": { "from": "2024-12-12T00:07:58.897Z", "to": "2024-12-12T00:13:41.090Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Информация об остановке",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT bus_stop_name, bus_stop_address FROM \"Bus_stops\" WHERE \"bus_stop_id\" = 14 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Количество пассажиров, ожидающих транспорт",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"datetime\" AT TIME ZONE 'UTC-3', ROUND (\r\n  AVG(\"number_of_passenger\") \r\n  OVER(ORDER BY \"datetime\" ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) , 0)\r\n  AS value\r\nFROM \"Passenger_Traffic\" WHERE \"bus_stop_id\" = 14 LIMIT 1440"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \"Bus_stop_adress\" FROM \"Bus_stops\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Максимальное время ожидания",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT max_waiting_time FROM \"Passenger_Waiting_Time\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Текущая загруженность",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT number_of_passenger FROM \"Passenger_Traffic\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Сведения о погоде",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT temperature, condition FROM \"Weather\" ORDER BY datetime DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Сведения о прибытии транспорта на остановку",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(\"datetime\", 'HH24:MI'), \"route_name\"  FROM \"Bus_Arrival\" WHERE \"bus_stop_id\" = 14 ORDER BY \"datetime\" DESC LIMIT 10\r\n"
    }
   ]
  },
  {
   "title": "Среднее время ожидания",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT datetime AT TIME ZONE 'UTC-3',\r\nROUND (\r\n  AVG(average_waiting_time ) \r\n  OVER(ORDER BY datetime ROWS BETWEEN 100 PRECEDING AND CURRENT ROW) , 0)\r\n  AS value\r\nFROM \"Passenger_Waiting_Time\" LIMIT 2000"
    }
   ]
  },
  {
   "title": "Сведения о трафике",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT traffic FROM \"Traffic\" LIMIT 50 "
    }
   ]
  }
 ]
}